### PR TITLE
✅ Add Codecov

### PR DESCRIPTION
**Pull request by xsc27**

### CODE REVIEW

**Comment by pelmini** [comment]
Could you clarify what the codecov report is saying?

**Comment by rally-carlos** [comment]
"The diff coverage is not available" because "no coverage uploaded for pull request base." This is the first time we are uploading a coverage report to Codecov.

Did you try "[Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit)"?

**Comment by xsc27** [comment]
"The diff coverage is not available" because "no coverage uploaded for pull request base." This is the first time we are uploading a coverage report to Codecov.

Did you try "[Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit)"?

**Comment by pelmini** [comment]
Sorry, I didn't notice that. Thanks for pointing that out!

**Review by pelmini — APPROVED** [review]

**Pull request merged**
