### PR TITLE
Basic Webpage Setup for Fizzbuzzx 

### PR DESCRIPTION
**Pull request by pelmini**

### CODE REVIEW

**Comment by xsc27** [comment]
- What is the deployment plan for this?
- Is this to interact with the API? If so, how?

**Review by xsc27 — CHANGES_REQUESTED** [review]
Looks like you are not using `pre-commit` :)

We need to enable more thorough formatting/style checks.

**Comment by pelmini** [comment]
- I was thinking of having the webpage interact with API and display the information grabbed from the API 
- Haven't thought much of a deployment plan, but would be nice to have when we do present just so that way people could interact with our product on their own if they would like to.

**Comment by xsc27** [comment]
I agree having a page to demo the API is a good nice-to-have.

I am not sure what value add this commit provides. Especially without a plan of how the frontend will talk to that backend.

**Comment by pelmini** [comment]
Do you want me leave it open or should I close it?

**Comment by xsc27** [comment]
Lets close for now.

**Pull request closed without merging**
